spring.application.name=manatee

# postgresql config
# spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://localhost:5432/manatee
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=*

# mybatis config
# mybatis.config=mybatis/mybatis-config.xml
mybatis.type-aliases-package=com.rathon.manatee.*.model,com.rathon.manatee.*.dto
mybatis.type-handlers-package=com.rathon.manatee.core.typeHandler;
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# MFA server config
# mfa.otp.url.verify=https://c887d6bbe34d.ngrok-free.app/api/v1/otp/checkOtpNum
mfa.otp.api.base=https://287eb6383147.ngrok-free.app
mfa.otp.api.verify=/api/v1/otp/checkOtpNum?cmpCd={companyId}&uid={username}&otpNum={otp}
mfa.otp.api.enroll=/api/v1/otp/unsafe
mfa.otp.api.delete=/api/v1/otp/user/{companyCd}/{userId}
mfa.bio.api.delete=/api/v1/fido/entity/{companyCd}/{userId}
mfa.otp.api.notify=/api/v1/push