spring.application.name=manatee

# postgresql config
# spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://localhost:5432/manatee
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# mybatis config
# mybatis.config=mybatis/mybatis-config.xml
mybatis.type-aliases-package=com.rathon.manatee.database.model;com.rathon.manatee.database.dto;com.rathon.manatee.community.model;com.rathon.manatee.community.dto
mybatis.type-handlers-package=com.rathon.manatee.community.typeHandler;
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true