spring.application.name=manatee
server.address=0.0.0.0
server.servlet.session.cookie.name=MANATEE_SESSIONID

# postgresql config
# spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://localhost:5432/manatee
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=*

# mybatis config
# mybatis.config=mybatis/mybatis-config.xml
mybatis.type-aliases-package=com.rathon.manatee.*.model,com.rathon.manatee.*.dto
mybatis.type-handlers-package=com.rathon.manatee.core.typeHandler;
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# MFA server config
mfa.base=https://b316-211-54-64-77.ngrok-free.app
#mfa.base=https://localhost:8443
mfa.key=48b8dd2c-4e37-4842-b160-9e32eaecfe65
mfa.otp.api.verify=/api/v1/otp/checkOtpNum?cmpCd={companyId}&uid={username}&otpNum={otp}
mfa.otp.api.enroll=/api/v1/otp/unsafe
mfa.otp.api.delete=/api/v1/otp/user/{companyCd}/{userId}
mfa.bio.api.delete=/api/v1/fido/user/{companyCd}/{userId}
mfa.otp.api.notify=/api/v1/push

mfa.acc.add=/api/v2/user
mfa.otp.add=/api/v2/otp/register
mfa.otp.vrf=/api/v2/otp/verify
mfa.otp.chk=/api/v2/otp/authenticate
mfa.fdo.add=/api/v2/fido2/register
mfa.fdo.vrf=/api/v2/fido2/verify
mfa.fdo.chk=/api/v2/fido2/authenticate